# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Runs at 17:00 UTC every day
    - cron: "0 17 * * *"

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: write # Needed to clone the repository
      pages: write # Needed to deploy to GitHub Pages

    steps:
      - name: Setup Repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: |
          deno --version
      - run: |
          deno run --allow-net --allow-read --allow-write scripts/wallpapers.ts
      - run: |
          deno run --allow-read --allow-write scripts/markdown.ts

      - name: Formatting
        run: deno fmt

      - name: Commit files
        run: |
          git config --local user.email "695601626@qq.com"
          git config --local user.name "linbingquan"
          deno run --allow-read --allow-run --allow-env scripts/git.ts

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Build
        run: deno task build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./packages/hono/dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
